Repository tari-project/bulletproofs-plus, pull requests merged in 2024-03, with the labels that each got.

#116 feat!: remove verifier RNG requirement
  benches/range_proof.rs
  src/protocols/transcript_protocol.rs
  src/range_proof.rs
  src/transcripts.rs
  src/utils/mod.rs
  src/utils/nullrng.rs
  tests/ristretto.rs
Labels: P-acks_required

#118 chore: arithmetic lint
  benches/range_proof.rs
  clippy.toml
  lints.toml
  src/range_proof.rs
  src/ristretto.rs
  src/transcripts.rs
  tests/ristretto.rs
Labels: P-acks_required

#113 ci: move to stable toolchain
  .github/workflows/clippy-check.yml
  .github/workflows/test.yml
  Cargo.toml
  src/range_proof.rs
Labels: P-acks_required

#121 fix: add missing dollar sign
  .github/workflows/source-cov.yml
Labels: CR-insufficient_context

#122 fix: update source coverage script
  test_coverage.sh
Labels: P-acks_required, P-reviews_required

#123 test: add tests for `NullRng`
  src/utils/nullrng.rs
Labels: CR-insufficient_context, P-acks_required

#127 fix: reduce verification vector allocation
  src/range_proof.rs
Labels: P-acks_required

#129 feat: remove partial precomputation
  Cargo.toml
  clippy.toml
  docs/quarkslab-audit/README.md
  src/range_proof.rs
  src/utils/generic.rs
Labels: P-acks_required
